version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravelphp:v1
        container_name: recipe_easy_api
        depends_on:
            - mysql
        volumes:
            - .:/var/www/html
        ports:
            - "8000:8000"
        working_dir: /var/www/html
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: recipe_easy_api
            DB_USERNAME: root
            DB_PASSWORD: password

    mysql:
        image: mysql:8.0
        container_name: mysql_container
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: recipe_easy_api

volumes:
    mysql_data:
